### ISSUE TITLE
Running react application with own webpack/babel configuration and not using create-react-app

### ISSUE THREAD

**Issue by nandeshwarshubh** [tilework/mosaic#60]
Hi,

We are using React without create-react-app, I did the webpack configuration and added injectWebpackConfig and injectBabelConfig to the webpack configuration files. But I am getting the following error when I spin up the webpack dev server - 
`ERROR in   Error: Child compilation failed:
  Module parse failed: Unexpected token (2:0)
  File was processed with these loaders:
   * ./node_modules/html-webpack-plugin/lib/loader.js
   * ./node_modules/@tilework/mosaic-webpack-import-loader/index.js
  You may need an additional loader to handle the result of these loaders.
  | Mosaic.setPlugins([]);
  > <!DOCTYPE html>
  | <html>`

Also, my css loader is also failing because mosaic is adding 'Mosaic.setPlugins([]);' the at the top of each css files-
`Module build failed (from ./node_modules/css-loader/dist/cjs.js):
CssSyntaxError

(1:1) /Users/~filelocation~/Component.module.css Unknown word

> 1 | Mosaic.setPlugins([]);
    | ^
  2 | .Component {}`

Is there a way where mosaic can probably skip adding 'Mosaic.setPlugins([]);' at the top of html and css files? or do you guys have custom injectors for such files?

**Comment by alfredsgenkins** [comment]
Hey! Pass an "entryMatcher" config to webpack inject loader. The typings for function are built-in in to the app. All configuration is available here: https://github.com/tilework/mosaic/blob/f061444d09295509923701f51f062d604e2a5193/integration/mosaic-config-injectors/typings/index.d.ts

**Comment by nandeshwarshubh** [comment]
> Hey!
> 
> Pass an "entryMatcher" config to webpack inject loader. The typings for function are built-in in to the app. All configuration is available here: https://github.com/tilework/mosaic/blob/f061444d09295509923701f51f062d604e2a5193/integration/mosaic-config-injectors/typings/index.d.ts
> 
> Make a function to match only select entry points. For NextJS, it is for example, `/[\\/]src[\\/]pages[\\/].+\.[jt]sx?/`.

Thank you so much, this fixed my issue :)
